2023-04-30 11:47:43,437 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 11:47:43,437 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 11:47:43,824 [django.request:241] [log:log_response] [ERROR] Internal Server Error: /factory/sync/query_instance/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\views.py", line 48, in get_instance
    data_ = online.query_instance()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\business\online_data_sync.py", line 20, in query_instance
    mysql_l = jsonpath(res.json(), '$..data[?(@.db_type=="mysql")].instance_name')
                       ^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-04-30 11:48:28,423 [django.request:241] [log:log_response] [ERROR] Internal Server Error: /factory/intranet/add/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'name' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\views.py", line 112, in add_intranet_config
    obj = DataFactoryIntranetConfig.objects.create(name=name, host=host, user=user, password=password, port=port,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\mysql\base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'name' cannot be null")
2023-04-30 11:48:28,558 [django.request:241] [log:log_response] [WARNING] Not Found: /favicon.ico
2023-04-30 11:56:20,205 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 11:56:20,206 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 11:56:20,635 [django.request:241] [log:log_response] [ERROR] Internal Server Error: /factory/sync/query_instance/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\views.py", line 48, in get_instance
    data_ = online.query_instance()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\business\online_data_sync.py", line 20, in query_instance
    mysql_l = jsonpath(res.json(), '$..data[?(@.db_type=="mysql")].instance_name')
                       ^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-04-30 11:56:28,348 [django.request:241] [log:log_response] [ERROR] Internal Server Error: /factory/intranet/add/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'name' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\views.py", line 112, in add_intranet_config
    obj = DataFactoryIntranetConfig.objects.create(name=name, host=host, user=user, password=password, port=port,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\mysql\base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'name' cannot be null")
2023-04-30 11:56:46,716 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 11:56:46,717 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 11:56:47,059 [django.request:241] [log:log_response] [ERROR] Internal Server Error: /factory/sync/query_instance/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\views.py", line 48, in get_instance
    data_ = online.query_instance()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\business\online_data_sync.py", line 20, in query_instance
    mysql_l = jsonpath(res.json(), '$..data[?(@.db_type=="mysql")].instance_name')
                       ^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-04-30 11:57:06,938 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 11:57:06,956 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 11:57:28,089 [django.request:241] [log:log_response] [ERROR] Internal Server Error: /factory/sync/query_instance/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 971, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\__init__.py", line 525, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 372, in decode
    obj, end = self.raw_decode(s)
               ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\simplejson\decoder.py", line 402, in raw_decode
    return self.scan_once(s, idx=_w(s, idx).end())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
simplejson.errors.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\views.py", line 48, in get_instance
    data_ = online.query_instance()
            ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\business\online_data_sync.py", line 20, in query_instance
    mysql_l = jsonpath(res.json(), '$..data[?(@.db_type=="mysql")].instance_name')
                       ^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\requests\models.py", line 975, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2023-04-30 11:57:28,119 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/favicon.ico
2023-04-30 11:57:37,740 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 11:57:37,741 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 11:57:47,957 [django.request:241] [log:log_response] [ERROR] Internal Server Error: /factory/intranet/add/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'name' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\views.py", line 112, in add_intranet_config
    obj = DataFactoryIntranetConfig.objects.create(name=name, host=host, user=user, password=password, port=port,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\mysql\base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'name' cannot be null")
2023-04-30 11:57:48,063 [django.request:241] [log:log_response] [WARNING] Not Found: /favicon.ico
2023-04-30 11:59:05,632 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 11:59:05,633 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:04:26,186 [django.request:241] [log:log_response] [ERROR] Internal Server Error: /factory/intranet/add/
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\mysql\base.py", line 75, in execute
    return self.cursor.execute(query, args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\cursors.py", line 206, in execute
    res = self._query(query)
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\cursors.py", line 319, in _query
    db.query(q)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\MySQLdb\connections.py", line 254, in query
    _mysql.connection.query(self, query)
MySQLdb.OperationalError: (1048, "Column 'name' cannot be null")

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\views\decorators\csrf.py", line 54, in wrapped_view
    return view_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\项目\data_factory_platform\data_sync\views.py", line 112, in add_intranet_config
    obj = DataFactoryIntranetConfig.objects.create(name=name, host=host, user=user, password=password, port=port,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 671, in create
    obj.save(force_insert=True, using=self.db)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 812, in save
    self.save_base(
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 863, in save_base
    updated = self._save_table(
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1006, in _save_table
    results = self._do_insert(
              ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\base.py", line 1047, in _do_insert
    return manager._insert(
           ^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\query.py", line 1790, in _insert
    return query.get_compiler(using=using).execute_sql(returning_fields)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\models\sql\compiler.py", line 1660, in execute_sql
    cursor.execute(sql, params)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 103, in execute
    return super().execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 67, in execute
    return self._execute_with_wrappers(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 80, in _execute_with_wrappers
    return executor(sql, params, many, context)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\utils.py", line 89, in _execute
    return self.cursor.execute(sql, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\admin\AppData\Local\Programs\Python\Python311\Lib\site-packages\django\db\backends\mysql\base.py", line 80, in execute
    raise IntegrityError(*tuple(e.args))
django.db.utils.IntegrityError: (1048, "Column 'name' cannot be null")
2023-04-30 12:04:29,738 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:04:29,739 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:05:38,461 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:05:38,463 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:07:36,847 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:07:36,848 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:08:35,158 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:08:35,159 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:09:45,302 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:09:45,303 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:13:26,530 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:13:26,533 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:14:09,392 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:14:09,400 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:14:27,433 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:14:27,435 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:15:04,650 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:15:04,651 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:19:19,963 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:19:19,965 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:19:45,243 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:19:45,245 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 12:33:06,150 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 12:33:06,154 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 16:10:04,967 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 16:10:04,968 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 16:16:00,220 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 16:16:00,221 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 16:16:37,000 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 16:16:37,018 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 16:18:21,139 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 16:18:21,140 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 16:21:36,943 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 16:21:36,944 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 16:25:14,147 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 16:25:14,148 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 16:25:28,272 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 16:25:28,284 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 16:25:50,791 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/favicon.ico
2023-04-30 16:59:50,668 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 16:59:50,669 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:00:10,734 [django.request:241] [log:log_response] [WARNING] Not Found: /favicon.ico
2023-04-30 17:02:11,428 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:02:11,437 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:02:33,585 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/favicon.ico
2023-04-30 17:08:15,437 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:08:15,438 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:08:55,638 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:08:55,639 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:10:16,262 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:10:16,266 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:12:07,255 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/intranet/static/images/logo-sm.png
2023-04-30 17:12:07,256 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/intranet/static/images/users/avatar-1.jpg
2023-04-30 17:12:07,416 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/intranet/static/images/favicon.ico
2023-04-30 17:12:12,742 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:12:12,744 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:12:59,864 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:12:59,873 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:13:29,270 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:13:29,271 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:13:48,332 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:13:48,336 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:16:02,579 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:16:02,580 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:16:19,399 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:16:19,400 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:16:20,211 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/favicon.ico
2023-04-30 17:22:48,350 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:22:48,375 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:30:17,160 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:30:17,161 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:32:53,391 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:32:53,393 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:36:08,253 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:36:08,255 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:40:36,215 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:40:36,216 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:41:21,218 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:41:21,219 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:47:39,211 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:47:39,212 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:48:43,733 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:48:43,733 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:51:55,545 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:51:55,547 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:53:44,234 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:53:44,236 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:54:45,511 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 17:54:45,515 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:55:40,766 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 17:55:40,769 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:08:21,421 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:08:21,422 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:08:47,205 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:08:47,208 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:10:48,098 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:10:48,100 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:11:24,533 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:11:24,534 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:11:44,629 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:11:44,630 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:13:10,691 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:13:10,693 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:13:30,875 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:13:30,877 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:13:34,891 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:13:34,892 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:19:58,466 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:19:58,466 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:20:14,848 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:20:14,849 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:20:44,089 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:20:44,091 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:22:18,165 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:22:18,167 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:23:31,264 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:23:31,265 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:23:57,138 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:23:57,139 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:29:22,342 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:29:22,343 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:29:34,953 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:29:34,956 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:34:17,995 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:34:17,998 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:40:36,294 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:40:36,298 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:44:29,102 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:44:29,105 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:50:00,726 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:50:00,727 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:50:54,160 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:50:54,161 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:52:01,688 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:52:01,689 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:52:09,980 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:52:09,982 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:52:25,321 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:52:25,321 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:52:41,282 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:52:41,284 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 18:59:32,810 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 18:59:32,811 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 19:00:51,332 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 19:00:51,335 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 19:21:57,041 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 19:21:57,043 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 19:22:23,902 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
2023-04-30 19:22:23,903 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 19:23:25,270 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/logo-sm.png
2023-04-30 19:23:25,272 [django.request:241] [log:log_response] [WARNING] Not Found: /factory/static/images/users/avatar-1.jpg
